-- AlterTable
ALTER TABLE "Feed" ADD COLUMN "lastNotifiedAt" DATETIME;
ALTER TABLE "Feed" ADD COLUMN "lastSeenAt" DATETIME;
ALTER TABLE "Feed" ADD COLUMN "checkIntervalMinutes" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Feed" ADD COLUMN "maxAgeMinutes" INTEGER NOT NULL DEFAULT 1440;

